[package]
name = "loc_etiq_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
iced = { version = "0.14.0", features = ["image"] }
serde = "1.0.22"
toml = "1.1.4"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Graphics_Printing",
] }
wmi = "0.18.3"

[build-dependencies]
embed-resource = "3.0"
winres = "0.1"